# Generated by Django 4.2.2 on 2023-06-12 18:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_user_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='is_verified',
        ),
    ]
