# Generated by Django 4.2.2 on 2023-06-14 20:54

from django.db import migrations, models
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Offer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('created_by', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('is_job', models.BooleanField()),
                ('offer_img', models.ImageField(blank=True, null=True, upload_to='offerimg')),
                ('date_created', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
