# Generated by Django 4.2.2 on 2023-06-28 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0002_alter_offer_id_alter_offer_offer_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='offer',
            name='id',
            field=models.IntegerField(default='abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789abcdefghijklmnopqrstuvwxyz0123456789', editable=False, primary_key=True, serialize=False),
        ),
    ]
