# Generated by Django 4.2.2 on 2023-06-28 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('offer', '0005_alter_offer_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='offer',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='offer',
            name='offer_pdf',
            field=models.FileField(blank=True, null=True, upload_to='offerpdfs'),
        ),
    ]
